language: php

env:
  global:
    - COMPOSER_ROOT_VERSION="4.0.x-dev"

matrix:
  include:
    - php: 5.6
      env:
        - DB=MYSQL
    - php: 7.0
      env:
        - DB=MYSQL
    - php: 7.1
      env:
        - DB=MYSQL
        #- PDO=1
    - php: 7.2
      env:
        - DB=MYSQL

before_script:
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  - composer validate
  - composer require --dev --no-update silverstripe/recipe-cms:1.0.x-dev
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - vendor/bin/phpunit
