mappings:
  MultisitesCMSMainExtension: 'Symbiote\Multisites\Admin\MultisitesCMSMainExtension'
  MultisitesCMSPageAddController: 'Symbiote\Multisites\Admin\MultisitesCMSPageAddController'
  MultisitesModelAdminExtension: 'Symbiote\Multisites\Admin\MultisitesModelAdminExtension'
  MultisitesFrontController: 'Symbiote\Multisites\Control\MultisitesFrontController'
  MultisitesRootController: 'Symbiote\Multisites\Control\MultisitesRootController'
  RobotsTxtController: 'Symbiote\Multisites\Control\RobotsTxtController'
  MultisitesAware: 'Symbiote\Multisites\Extension\MultisitesAware'
  MultisitesContentControllerExtension: 'Symbiote\Multisites\Extension\MultisitesContentControllerExtension'
  MultisitesControllerExtension: 'Symbiote\Multisites\Extension\MultisitesControllerExtension'
  MultisitesErrorPageExtension: 'Symbiote\Multisites\Extension\MultisitesErrorPageExtension'
  MultisitesFileFieldExtension: 'Symbiote\Multisites\Extension\MultisitesFileFieldExtension'
  MultisitesHtmlEditorField_ToolbarExtension: 'Symbiote\Multisites\Extension\MultisitesHtmlEditorField_ToolbarExtension'
  MultisitesMemberExtension: 'Symbiote\Multisites\Extension\MultisitesMemberExtension'
  MultisitesReport: 'Symbiote\Multisites\Extension\MultisitesReport'
  MultisitesSecurityExtension: 'Symbiote\Multisites\Extension\MultisitesSecurityExtension'
  MultisitesSiteConfigExtension: 'Symbiote\Multisites\Extension\MultisitesSiteConfigExtension'
  MultisitesSiteTreeExtension: 'Symbiote\Multisites\Extension\MultisitesSiteTreeExtension'
  SiteSearchForm: 'Symbiote\Multisites\Form\SiteSearchForm'
  MultisitesInitAssetsTask: 'Symbiote\Multisites\Job\MultisitesInitAssetsTask'
  TidySiteTask: 'Symbiote\Multisites\Job\TidySiteTask'
  Site: 'Symbiote\Multisites\Model\Site'
  Multisites: 'Symbiote\Multisites\Multisites'
  MultisiteSiteTest: 'Symbiote\Multisites\Tests\MultisiteSiteTest'
