---
Name: modelascontrollerroutes
Before: framework/routes#coreroutes
After: cms/routes#modelascontrollerroutes
---
Director:
  rules:
    '': MultisitesRootController
    'robots.txt': 'RobotsTxtController'
    '$URLSegment//$Action/$ID/$OtherID': MultisitesFrontController

